#!/usr/bin/env python3
"""
provide asynchronous list comprehension that
returns list of floats
"""
from typing import List
from importlib import import_module as using
async_generator = using('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Returns List of floats generated by the async_generator.
    """
    return [i async for i in async_generator()]
